INSERT INTO BOTTLE_TYPE (TYPE_ID, TYPE_NAME, CREATE_DATE, UPDATE_DATE) VALUES
(1, 'Vin', DATETIME('now'), DATETIME('now'));
INSERT INTO BOTTLE_TYPE (TYPE_ID, TYPE_NAME, CREATE_DATE, UPDATE_DATE) VALUES
(2, 'Whisky', DATETIME('now'), DATETIME('now'));
INSERT INTO BOTTLE_TYPE (TYPE_ID, TYPE_NAME, CREATE_DATE, UPDATE_DATE) VALUES
(3, 'Ruhm', DATETIME('now'), DATETIME('now'));
INSERT INTO BOTTLE_TYPE (TYPE_ID, TYPE_NAME, CREATE_DATE, UPDATE_DATE) VALUES
(4, 'Vodka', DATETIME('now'), DATETIME('now'));
INSERT INTO BOTTLE_TYPE (TYPE_ID, TYPE_NAME, CREATE_DATE, UPDATE_DATE) VALUES
(5, 'Autres liqueurs', DATETIME('now'), DATETIME('now'));
